[package]
name = "vault_program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.0"
solana-program = "1.18.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

